import type { ColumnSchema, ModuleDefinition, ModuleKey } from '../services/supabase/types'

const commonReadOnly = ['id', 'created_at', 'updated_at']

export const modules: ModuleDefinition[] = [
  {
    key: 'properties',
    title: 'Propiedades',
    singular: 'propiedad',
    description: 'Inventario de inmuebles y unidades administradas.',
    table: {
      name: 'propiedades',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['numero_registro_propiedad', 'integer', false],
        ['tipo_propiedad', 'string', false],
        ['tipo_propiedad_id', 'string', false, 'tipos_propiedad', ['tipo_propiedad', 'nombre']],
        ['direccion', 'string'],
        ['ciudad', 'string', false],
        ['cp', 'string', false],
        ['pais', 'string', false],
        ['monto_contrato', 'number', false],
        ['comision', 'integer', false],
        ['superficie_parcela', 'integer', false],
        ['superficie_construida', 'integer', false],
        ['numeros_dormitorios', 'integer', false],
        ['numeros_banos', 'integer', false],
        ['jardin', 'boolean', false],
        ['piscina', 'boolean', false],
        ['garage', 'boolean', false],
        ['nueva_segunda_mano', 'string', false],
        ['observaciones', 'string', false],
        ['adjuntos', 'string', false],
        ['fotos', 'string', false],
        ['documentacion', 'string', false],
        ['historial', 'string', false],
        ['alquilada', 'boolean', false],
        ['cartel', 'boolean', false],
        ['estado', 'string'],
        ['propietario_id', 'string', false, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
      ]),
    },
  },
  {
    key: 'owners',
    title: 'Propietarios',
    singular: 'propietario',
    description: 'Personas o entidades titulares de propiedades.',
    table: {
      name: 'propietarios',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dni', 'integer', false],
        ['nombres', 'string', false],
        ['apellidos', 'string', false],
        ['telefono', 'string', false],
        ['celular', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['cp', 'string', false],
        ['pais', 'string', false],
        ['empresa', 'string', false],
        ['cuit_empresa', 'string', false],
        ['caracter', 'string', false],
        ['conyuge', 'string', false],
        ['dni_conyuge', 'string', false],
        ['observaciones', 'string', false],
        ['cliente_id', 'string', false, 'clientes', ['nombres', 'apellidos']],
        ['cbu', 'string', false],
        ['alias_cbu', 'string', false],
        ['historial_cobros', 'string', false],
      ]),
    },
  },
  {
    key: 'tenants',
    title: 'Locatarios',
    singular: 'locatario',
    description: 'Locatarios, inquilinos y contactos vinculados.',
    table: {
      name: 'inquilinos',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['cliente_id', 'string', false, 'clientes', ['nombres', 'apellidos']],
        ['dni', 'integer', false],
        ['nombres', 'string', false],
        ['apellidos', 'string', false],
        ['telefono', 'string', false],
        ['celular_locatario', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['cp', 'string', false],
        ['pais', 'string', false],
        ['comentarios', 'string', false],
        ['nombre_garante', 'string', false],
        ['dni_garante', 'string', false],
        ['domicilio_garante', 'string', false],
        ['vivienda_garantia', 'string', false],
        ['matr_vivienda_garantia', 'string', false],
        ['documentacion', 'string', false],
        ['historial_contratos', 'string', false],
        ['fecha_alta', 'datetime', false],
      ]),
    },
  },
  {
    key: 'contracts',
    title: 'Contratos',
    singular: 'contrato',
    description: 'Contratos de alquiler con fechas, partes y estado.',
    table: {
      name: 'contratos_alquiler',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['id_locacion', 'integer', false],
        ['numero_registro_propiedad', 'integer', false],
        ['propiedad_id', 'string', true, 'propiedades', ['direccion']],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['inquilino_id', 'string', true, 'inquilinos', ['nombres', 'apellidos']],
        ['plazo_contrato_id', 'string', false, 'plazos_contrato', ['equivale', 'nombre', 'dias']],
        ['moneda_cobro_id', 'string', false, 'monedas_cobro', ['codigo', 'nombre']],
        ['tipo_actualizacion_valor_id', 'string', false, 'tipos_actualizacion_valor', ['nombre']],
        ['renovacion_de_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['plazo_dias', 'integer', false],
        ['fecha_locacion', 'datetime', false],
        ['fecha_fin_contrato', 'datetime', false],
        ['fecha_renovacion', 'date', false],
        ['fecha_actualizacion_valor', 'date', false],
        ['ajuste_alquiler', 'number', false],
        ['tipo_ajuste', 'string', false],
        ['porcentaje_ajuste', 'number', false],
        ['comision_inmobiliaria', 'number', false],
        ['fecha_inicio', 'date'],
        ['fecha_fin', 'date'],
        ['dni_locatario', 'integer', false],
        ['dni_locador', 'integer', false],
        ['dni_empleado', 'integer', false],
        ['observaciones', 'string', false],
        ['cuota_1', 'number', false],
        ['cuota_2', 'number', false],
        ['cuota_3', 'number', false],
        ['cuota_4', 'number', false],
        ['gastos_paga_locador', 'string', false],
        ['gastos_paga_inmo', 'string', false],
        ['nota_para_locador', 'string', false],
        ['nota_para_locatario', 'string', false],
        ['documentacion_para_entregar', 'boolean', false],
        ['nro_sum_luz', 'integer', false],
        ['nro_sum_agua', 'integer', false],
        ['nro_sum_gas', 'string', false],
        ['luz_paga', 'string', false],
        ['agua_paga', 'string', false],
        ['gas_paga', 'string', false],
        ['multa', 'number', false],
        ['observaciones_multa', 'string', false],
        ['archivo_contrato', 'string', false],
        ['estado', 'string'],
      ]),
    },
  },
  {
    key: 'payments',
    title: 'Cobros',
    singular: 'pago',
    description: 'Registro de pagos mensuales, cuotas, recibos, gastos y estados.',
    table: {
      name: 'pagos_alquiler',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['legacy_id', 'integer', false],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['cuota_id', 'string', true, 'cuotas_alquiler', ['concepto', 'periodo', 'fecha_vencimiento']],
        ['fecha_vencimiento', 'date', false],
        ['fecha_pago', 'datetime'],
        ['id_locacion', 'integer', false],
        ['mes', 'string', false],
        ['anio', 'integer', false],
        ['concepto', 'string'],
        ['cuota_mensual', 'number', false],
        ['comision', 'integer', false],
        ['detalle_otros_importes', 'string', false],
        ['otros_importes', 'number', false],
        ['detalle_otros_importes_1', 'string', false],
        ['otros_importes_1', 'number', false],
        ['recibo', 'string', false],
        ['recibo_locatario', 'string', false],
        ['gastos_adicionales', 'number', false],
        ['liquidacion_propietario', 'number', false],
        ['detalle_otros_importes_2', 'string', false],
        ['otros_importes_2', 'number', false],
        ['detalle_otros_importes_3', 'string', false],
        ['otros_importes_3', 'number', false],
        ['cuota_paga', 'integer', false],
        ['total_cuotas', 'integer', false],
        ['entrega', 'number', false],
        ['total_recibo_locatario', 'number', false],
        ['resto_alquiler', 'number', false],
        ['alquiler_locador', 'number', false],
        ['importe', 'number', false],
        ['estado', 'string', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'ownerCollections',
    title: 'Liquidaciones propietarios',
    singular: 'liquidacion propietario',
    description: 'Importes liquidados o cobrados por propietarios segun lo pactado.',
    table: {
      name: 'cobros_propietario',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['moneda_cobro_id', 'string', false, 'monedas_cobro', ['codigo', 'nombre']],
        ['fecha_cobro', 'date'],
        ['concepto', 'string'],
        ['importe', 'number'],
        ['estado', 'string', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'agenda',
    title: 'Agenda y alertas',
    singular: 'evento',
    description: 'Recordatorios, vencimientos, cuotas impagas y seguimiento documental.',
    table: {
      name: 'agenda_alertas',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['titulo', 'string'],
        ['tipo', 'string', false, undefined, undefined, [
          { value: 'contrato_por_vencer', label: 'Contrato por vencer' },
          { value: 'cuota_impaga', label: 'Cuota impaga' },
          { value: 'documentacion', label: 'Documentacion' },
          { value: 'recordatorio', label: 'Recordatorio' },
        ]],
        ['fecha', 'datetime'],
        ['estado', 'string', false, undefined, undefined, [
          { value: 'pendiente', label: 'Pendiente' },
          { value: 'en_proceso', label: 'En proceso' },
          { value: 'resuelto', label: 'Resuelto' },
        ]],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propiedad_id', 'string', false, 'propiedades', ['direccion']],
        ['inquilino_id', 'string', false, 'inquilinos', ['nombres', 'apellidos']],
        ['propietario_id', 'string', false, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['descripcion', 'string', false],
        ['automatico', 'boolean', false],
        ['fecha_recordatorio', 'datetime', false],
        ['documento_pendiente', 'string', false],
      ]),
    },
  },
  {
    key: 'employees',
    title: 'Empleados',
    singular: 'empleado',
    description: 'Usuarios internos y empleados de la inmobiliaria.',
    table: {
      name: 'empleados',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dni', 'integer', false],
        ['nombres', 'string'],
        ['apellido', 'string', false],
        ['telefono', 'string', false],
        ['celular', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['codigo_postal', 'string', false],
        ['pais', 'string', false],
        ['foto', 'string', false],
        ['rol', 'string', false, undefined, undefined, [
          { value: 'superadmin', label: 'Super administrador' },
          { value: 'admin', label: 'Administrador' },
          { value: 'empleado', label: 'Empleado' },
        ]],
        ['activo', 'boolean', false],
        ['user_id', 'string', false, 'user_profiles', ['email', 'role']],
      ]),
    },
  },
  {
    key: 'contractOwners',
    title: 'Propietarios por contrato',
    singular: 'propietario por contrato',
    description: 'Vinculos multiples entre contratos y propietarios.',
    table: {
      name: 'contrato_propietarios',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['porcentaje', 'number', false],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'contractTenants',
    title: 'Inquilinos por contrato',
    singular: 'inquilino por contrato',
    description: 'Vinculos multiples entre contratos e inquilinos.',
    table: {
      name: 'contrato_inquilinos',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['inquilino_id', 'string', true, 'inquilinos', ['nombres', 'apellidos']],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'userRoles',
    title: 'Equipo',
    singular: 'miembro del equipo',
    description: 'Usuarios internos, invitaciones y roles de acceso al sistema.',
    table: {
      name: 'user_profiles',
      primaryKey: 'id',
      canCreate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['email', 'string', true],
        ['role', 'string', false, undefined, undefined, [
          { value: 'superadmin', label: 'Super administrador' },
          { value: 'admin', label: 'Administrador' },
          { value: 'user', label: 'Usuario sin acceso al panel' },
        ]],
      ]),
    },
  },
  {
    key: 'propertyTypes',
    title: 'Tipos de propiedades',
    singular: 'tipo de propiedad',
    description: 'Configuracion de categorias para clasificar propiedades.',
    table: {
      name: 'tipos_propiedad',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['tipo_propiedad', 'string'],
        ['nombre', 'string'],
        ['descripcion', 'string', false],
      ]),
    },
  },
  {
    key: 'contractTerms',
    title: 'Plazos de contratos',
    singular: 'plazo de contrato',
    description: 'Configuracion de duraciones disponibles para contratos de alquiler.',
    table: {
      name: 'plazos_contrato',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dias', 'integer', false],
        ['caracter', 'string', false],
        ['equivale', 'string', false],
        ['nombre', 'string'],
        ['meses', 'integer'],
        ['descripcion', 'string', false],
      ]),
    },
  },
  {
    key: 'currencies',
    title: 'Monedas de cobro',
    singular: 'moneda de cobro',
    description: 'Configuracion de monedas disponibles para importes y cobros.',
    table: {
      name: 'monedas_cobro',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['codigo', 'string'],
        ['nombre', 'string'],
        ['simbolo', 'string', false],
        ['dolar', 'number', false],
        ['euro', 'number', false],
      ]),
    },
  },
  {
    key: 'updateTypes',
    title: 'Tipos de actualizacion',
    singular: 'tipo de actualizacion',
    description: 'Configuracion de criterios para actualizar el valor del contrato.',
    table: {
      name: 'tipos_actualizacion_valor',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['nombre', 'string'],
        ['descripcion', 'string', false],
        ['activo', 'boolean', false],
      ]),
    },
  },
]

export function getModule(key: Exclude<ModuleKey, 'dashboard'>): ModuleDefinition {
  return modules.find((module) => module.key === key) ?? modules[0]
}

function columns(
  definitions: Array<
    [
      name: string,
      type: ColumnSchema['type'],
      readOnly?: boolean,
      referenceTable?: string,
      labelColumns?: string[],
      options?: ColumnSchema['options'],
    ]
  >,
): ColumnSchema[] {
  return definitions.map(([name, type, readOnly = false, referenceTable, labelColumns, options]) => ({
    name,
    type,
    nullable: !['id', 'fecha_inicio', 'fecha_fin', 'fecha', 'importe', 'estado'].includes(name),
    required: ['fecha_inicio', 'fecha_fin', 'fecha', 'importe', 'estado'].includes(name),
    readOnly: readOnly || commonReadOnly.includes(name),
    reference: referenceTable
      ? {
          table: referenceTable,
          valueColumn: 'id',
          labelColumns: labelColumns ?? ['nombre'],
        }
      : undefined,
    options,
  }))
}
