import type { ColumnSchema, ModuleDefinition, ModuleKey } from '../services/supabase/types'

const commonReadOnly = ['id', 'created_at', 'updated_at']

export const modules: ModuleDefinition[] = [
  {
    key: 'clients',
    title: 'Clientes',
    singular: 'cliente',
    description: 'Registro maestro de personas vinculadas a la inmobiliaria.',
    createLabel: 'Nuevo cliente',
    table: {
      name: 'clientes',
      primaryKey: 'id',
      columns: columns([
        ['nombres', 'string', false, undefined, undefined, undefined, true],
        ['apellidos', 'string', false, undefined, undefined, undefined, true],
        ['dni', 'integer', false, undefined, undefined, undefined, true],
        ['cuit', 'string', false, undefined, undefined, undefined, true],
        ['telefono', 'string', false, undefined, undefined, undefined, true],
        ['es_propietario', 'boolean', false],
        ['es_inquilino', 'boolean', false],
        ['es_garante', 'boolean', false],
        ['email', 'string', false, undefined, undefined, undefined, true],
        ['direccion', 'string', false, undefined, undefined, undefined, true],
        ['ciudad', 'string', false, undefined, undefined, undefined, true],
        ['cp', 'string', false, undefined, undefined, undefined, true],
        ['pais', 'string', false, undefined, undefined, undefined, true],
        ['fecha_alta', 'datetime', false],
        ['id', 'string', true],
      ]),
    },
  },
  {
    key: 'properties',
    title: 'Inmuebles',
    singular: 'inmueble',
    description: 'Inmuebles administrados y sus propietarios vinculados.',
    createLabel: 'Nuevo inmueble',
    table: {
      name: 'propiedades',
      primaryKey: 'id',
      columns: columns([
        ['tipo_propiedad_id', 'string', false, 'tipos_propiedad', ['tipo_propiedad', 'nombre'], undefined, true],
        ['direccion', 'string', false, undefined, undefined, undefined, true],
        ['titulares_ids', 'json', false, 'propietarios', ['apellidos', 'nombres', 'dni'], undefined, true, undefined, true],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['ciudad', 'string', false, undefined, undefined, undefined, true],
        ['cp', 'string', false, undefined, undefined, undefined, true],
        ['pais', 'string', false, undefined, undefined, undefined, true],
        ['estado', 'string', false, undefined, undefined, [
          { value: 'disponible', label: 'Disponible' },
          { value: 'reservada', label: 'Reservada' },
          { value: 'alquilada', label: 'Alquilada' },
          { value: 'mantenimiento', label: 'En mantenimiento' },
        ], true],
        ['canon_pretendido', 'number', false, undefined, undefined, undefined, true],
        ['destino_habilitado', 'string', false, undefined, undefined, [
          { value: 'vivienda', label: 'Vivienda' },
          { value: 'comercial', label: 'Comercial' },
          { value: 'mixto', label: 'Vivienda o comercial' },
        ], true],
        ['numero_registro_propiedad', 'integer', false],
        ['partida_inmobiliaria', 'string', false],
        ['regimen_propiedad_horizontal', 'boolean', false],
        ['unidad_funcional', 'string', false],
        ['piso_departamento', 'string', false],
        ['superficie_parcela', 'integer', false],
        ['superficie_cubierta', 'number', false],
        ['numeros_dormitorios', 'integer', false],
        ['numeros_banos', 'integer', false],
        ['garage', 'boolean', false],
        ['jardin', 'boolean', false],
        ['piscina', 'boolean', false],
        ['composicion', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['estado_conservacion', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['colores_pintura', 'string', false],
        ['incluye_muebles', 'boolean', false],
        ['descripcion_muebles_accesorios', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['inventario', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['tiene_expensas', 'boolean', false],
        ['expensas_aproximadas', 'number', false],
        ['administracion_consorcio', 'string', false],
        ['reglamento_copropiedad', 'boolean', false],
        ['rubro_comercial_permitido', 'string', false],
        ['mascotas_permitidas', 'boolean', false],
        ['restricciones_instalaciones', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['linea_telefonica_incluida', 'boolean', false],
        ['nro_suministro_luz', 'string', false],
        ['nro_suministro_agua', 'string', false],
        ['nro_suministro_gas', 'string', false],
        ['servicio_luz_activo', 'boolean', false],
        ['servicio_agua_activo', 'boolean', false],
        ['servicio_gas_activo', 'boolean', false],
        ['cantidad_llaves', 'integer', false],
        ['observaciones', 'string', false, undefined, undefined, undefined, false, 'textarea'],
        ['fotos', 'string', true],
        ['documentacion', 'string', false],
        ['alquilada', 'boolean', true],
        ['id', 'string', true],
      ]),
    },
  },
  {
    key: 'owners',
    title: 'Propietarios',
    singular: 'propietario',
    description: 'Personas o entidades titulares de propiedades.',
    table: {
      name: 'propietarios',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dni', 'integer', false],
        ['nombres', 'string', false],
        ['apellidos', 'string', false],
        ['telefono', 'string', false],
        ['celular', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['cp', 'string', false],
        ['pais', 'string', false],
        ['empresa', 'string', false],
        ['cuit_empresa', 'string', false],
        ['caracter', 'string', false],
        ['conyuge', 'string', false],
        ['dni_conyuge', 'string', false],
        ['observaciones', 'string', false],
        ['cliente_id', 'string', false, 'clientes', ['nombres', 'apellidos']],
        ['cbu', 'string', false],
        ['alias_cbu', 'string', false],
        ['historial_cobros', 'string', false],
      ]),
    },
  },
  {
    key: 'propertyOwners',
    title: 'Propietarios por inmueble',
    singular: 'propietario vinculado',
    description: 'Tabla puente que vincula inmuebles con uno o mas propietarios.',
    table: {
      name: 'propiedad_propietarios',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['propiedad_id', 'string', false, 'propiedades', ['direccion']],
        ['propietario_id', 'string', false, 'propietarios', ['apellidos', 'nombres', 'dni']],
        ['porcentaje', 'number', false],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'tenants',
    title: 'Locatarios',
    singular: 'locatario',
    description: 'Locatarios, inquilinos y contactos vinculados.',
    table: {
      name: 'inquilinos',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['cliente_id', 'string', false, 'clientes', ['nombres', 'apellidos']],
        ['dni', 'integer', false],
        ['nombres', 'string', false],
        ['apellidos', 'string', false],
        ['telefono', 'string', false],
        ['celular_locatario', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['cp', 'string', false],
        ['pais', 'string', false],
        ['comentarios', 'string', false],
        ['nombre_garante', 'string', false],
        ['dni_garante', 'string', false],
        ['domicilio_garante', 'string', false],
        ['garante_cliente_id', 'string', false, 'clientes', ['nombres', 'apellidos', 'dni']],
        ['vivienda_garantia', 'string', false],
        ['matr_vivienda_garantia', 'string', false],
        ['documentacion', 'string', false],
        ['historial_contratos', 'string', false],
        ['fecha_alta', 'datetime', false],
      ]),
    },
  },
  {
    key: 'contracts',
    title: 'Locaciones',
    singular: 'locación',
    description: 'Locaciones, condiciones acordadas y contratos generados.',
    table: {
      name: 'contratos_alquiler',
      primaryKey: 'id',
      canCreate: false,
      columns: columns([
        ['id', 'string', true],
        ['id_locacion', 'integer', false],
        ['numero_registro_propiedad', 'integer', false],
        ['propiedad_id', 'string', true, 'propiedades', ['direccion']],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['inquilino_id', 'string', true, 'inquilinos', ['nombres', 'apellidos']],
        ['propietarios_ids', 'json', false, 'propietarios', ['apellidos', 'nombres', 'dni'], undefined, false, undefined, true],
        ['inquilinos_ids', 'json', false, 'inquilinos', ['apellidos', 'nombres', 'dni'], undefined, false, undefined, true],
        ['garantes_ids', 'json', false, 'garantes', ['apellidos', 'nombres', 'dni'], undefined, false, undefined, true],
        ['plazo_contrato_id', 'string', false, 'plazos_contrato', ['equivale', 'nombre', 'dias']],
        ['moneda_cobro_id', 'string', false, 'monedas_cobro', ['codigo', 'nombre']],
        ['tipo_actualizacion_valor_id', 'string', false, 'tipos_actualizacion_valor', ['nombre']],
        ['renovacion_de_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['plazo_dias', 'integer', false],
        ['plazo_meses', 'integer', false],
        ['fecha_locacion', 'datetime', false],
        ['fecha_fin_contrato', 'datetime', false],
        ['fecha_renovacion', 'date', false],
        ['fecha_actualizacion_valor', 'date', false],
        ['ajuste_alquiler', 'number', false],
        ['tipo_ajuste', 'string', false],
        ['porcentaje_ajuste', 'number', false],
        ['comision_inmobiliaria', 'number', false],
        ['porcentaje_comision_inmobiliaria', 'number', false],
        ['fecha_inicio', 'date'],
        ['fecha_fin', 'date'],
        ['dni_locatario', 'integer', false],
        ['dni_locador', 'integer', false],
        ['dni_empleado', 'integer', false],
        ['observaciones', 'string', false],
        ['gastos_paga_locador', 'string', false],
        ['gastos_paga_inmo', 'string', false],
        ['nota_para_locador', 'string', false],
        ['nota_para_locatario', 'string', false],
        ['documentacion_para_entregar', 'boolean', false],
        ['nro_sum_luz', 'integer', false],
        ['nro_sum_agua', 'integer', false],
        ['nro_sum_gas', 'string', false],
        ['luz_paga', 'string', false],
        ['agua_paga', 'string', false],
        ['gas_paga', 'string', false],
        ['multa', 'number', false],
        ['observaciones_multa', 'string', false],
        ['archivo_contrato', 'string', false],
        ['plantilla_contrato', 'string', false, undefined, undefined, [
          { value: 'vivienda_con_expensas', label: 'Vivienda con expensas' },
          { value: 'vivienda_sin_expensas', label: 'Vivienda sin expensas' },
          { value: 'comercial_con_expensas', label: 'Comercial con expensas' },
          { value: 'comercial_sin_expensas', label: 'Comercial sin expensas' },
        ]],
        ['destino_locacion', 'string', false],
        ['canon_inicial', 'number', false],
        ['monto_inicial', 'number', false],
        ['monto_actual', 'number', false],
        ['frecuencia_ajuste', 'integer', false],
        ['tipo_indice', 'string', false],
        ['proxima_fecha_ajuste', 'date', false],
        ['icl_base', 'number', false],
        ['deposito_garantia', 'number', false],
        ['incluye_expensas', 'boolean', false],
        ['datos_documento', 'json', false],
        ['contenido_contrato', 'string', false],
        ['fecha_generacion', 'datetime', true],
        ['estado', 'string'],
      ]),
    },
  },
  {
    key: 'contractOwners',
    title: 'Propietarios por contrato',
    singular: 'propietario de contrato',
    description: 'Tabla puente entre contratos y propietarios.',
    table: {
      name: 'contrato_propietarios',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propietario_id', 'string', false, 'propietarios', ['apellidos', 'nombres', 'dni']],
        ['porcentaje', 'number', false],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'contractTenants',
    title: 'Inquilinos por contrato',
    singular: 'inquilino de contrato',
    description: 'Tabla puente entre contratos e inquilinos.',
    table: {
      name: 'contrato_inquilinos',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['inquilino_id', 'string', false, 'inquilinos', ['apellidos', 'nombres', 'dni']],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'contractGuarantors',
    title: 'Garantes por contrato',
    singular: 'garante de contrato',
    description: 'Tabla puente entre contratos y garantes.',
    table: {
      name: 'contrato_garantes',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['garante_id', 'string', false, 'garantes', ['apellidos', 'nombres', 'dni']],
        ['principal', 'boolean', false],
      ]),
    },
  },
  {
    key: 'payments',
    title: 'Ingresos',
    singular: 'ingreso',
    description: 'Ingresos registrados por alquileres, cuotas, recibos y otros conceptos.',
    table: {
      name: 'pagos_alquiler',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['legacy_id', 'integer', false],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['cuota_id', 'string', false, 'cuotas_alquiler', ['numero_cuota', 'fecha_vencimiento']],
        ['fecha_vencimiento', 'date', false],
        ['fecha_pago', 'datetime'],
        ['id_locacion', 'integer', false],
        ['mes', 'string', false],
        ['anio', 'integer', false],
        ['concepto', 'string'],
        ['cuota_mensual', 'number', false],
        ['comision', 'integer', false],
        ['detalle_otros_importes', 'string', false],
        ['otros_importes', 'number', false],
        ['detalle_otros_importes_1', 'string', false],
        ['otros_importes_1', 'number', false],
        ['recibo', 'string', false],
        ['recibo_locatario', 'string', false],
        ['gastos_adicionales', 'number', false],
        ['liquidacion_propietario', 'number', false],
        ['detalle_otros_importes_2', 'string', false],
        ['otros_importes_2', 'number', false],
        ['detalle_otros_importes_3', 'string', false],
        ['otros_importes_3', 'number', false],
        ['cuota_paga', 'integer', false],
        ['total_cuotas', 'integer', false],
        ['entrega', 'number', false],
        ['total_recibo_locatario', 'number', false],
        ['resto_alquiler', 'number', false],
        ['alquiler_locador', 'number', false],
        ['importe', 'number', false],
        ['tipo_movimiento', 'string', false, undefined, undefined, [
          { value: 'ingreso', label: 'Ingreso' },
          { value: 'egreso', label: 'Egreso' },
        ]],
        ['porcentaje_comision', 'number', false],
        ['importe_comision', 'number', false],
        ['saldo_propietario', 'number', false],
        ['pagador_nombre', 'string', false],
        ['medio_pago', 'string', false],
        ['numero_recibo', 'string', false],
        ['recibo_datos', 'json', false],
        ['estado', 'string', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'rentInstallments',
    title: 'Cuotas de alquiler',
    singular: 'cuota',
    description: 'Cuotas mensuales generadas por contrato para deuda, vencimientos e imputacion de pagos.',
    table: {
      name: 'cuotas_alquiler',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['numero_cuota', 'integer'],
        ['periodo_inicio', 'date'],
        ['periodo_fin', 'date'],
        ['fecha_vencimiento', 'date'],
        ['importe', 'number'],
        ['saldo', 'number', false],
        ['estado', 'string', false, undefined, undefined, [
          { value: 'pendiente', label: 'Pendiente' },
          { value: 'parcial', label: 'Parcial' },
          { value: 'pagada', label: 'Pagada' },
          { value: 'vencida', label: 'Vencida' },
          { value: 'anulada', label: 'Anulada' },
        ]],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'cashMovements',
    title: 'Movimientos de caja',
    singular: 'movimiento',
    description: 'Arqueo de caja con ingresos, egresos, comisiones y saldos.',
    table: {
      name: 'movimientos_caja',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['fecha', 'datetime'],
        ['tipo', 'string', false, undefined, undefined, [
          { value: 'ingreso', label: 'Ingreso' },
          { value: 'egreso', label: 'Egreso' },
        ]],
        ['concepto', 'string'],
        ['importe', 'number'],
        ['origen', 'string', false],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['cuota_id', 'string', false, 'cuotas_alquiler', ['numero_cuota', 'fecha_vencimiento']],
        ['pago_id', 'string', false, 'pagos_alquiler', ['numero_recibo', 'fecha_pago']],
        ['propietario_id', 'string', false, 'propietarios', ['apellidos', 'nombres', 'dni']],
        ['cliente_id', 'string', false, 'clientes', ['apellidos', 'nombres', 'numero_documento']],
        ['porcentaje_comision', 'number', false],
        ['importe_comision', 'number', false],
        ['saldo_propietario', 'number', false],
        ['pagador_nombre', 'string', false],
        ['medio_pago', 'string', false],
        ['numero_recibo', 'string', false],
        ['recibo_datos', 'json', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'ownerCollections',
    title: 'Liquidaciones propietarios',
    singular: 'liquidacion propietario',
    description: 'Importes liquidados o cobrados por propietarios segun lo pactado.',
    table: {
      name: 'cobros_propietario',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propietario_id', 'string', true, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['moneda_cobro_id', 'string', false, 'monedas_cobro', ['codigo', 'nombre']],
        ['fecha_cobro', 'date'],
        ['concepto', 'string'],
        ['importe', 'number'],
        ['estado', 'string', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'ownerSettlements',
    title: 'Liquidaciones',
    singular: 'liquidacion',
    description: 'Liquidaciones formales a propietarios para emision y seguimiento.',
    table: {
      name: 'liquidaciones_propietario',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['propietario_id', 'string', false, 'propietarios', ['apellidos', 'nombres', 'dni']],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['fecha', 'date'],
        ['periodo_desde', 'date', false],
        ['periodo_hasta', 'date', false],
        ['subtotal_alquiler', 'number', false],
        ['total_comision', 'number', false],
        ['total_gastos', 'number', false],
        ['total_a_transferir', 'number', false],
        ['estado', 'string', false, undefined, undefined, [
          { value: 'borrador', label: 'Borrador' },
          { value: 'emitida', label: 'Emitida' },
          { value: 'pagada', label: 'Pagada' },
          { value: 'anulada', label: 'Anulada' },
        ]],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'settlementDetails',
    title: 'Detalle de liquidaciones',
    singular: 'detalle de liquidacion',
    description: 'Conceptos que componen cada liquidacion de propietario.',
    table: {
      name: 'liquidaciones_detalle',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['liquidacion_id', 'string', false, 'liquidaciones_propietario', ['fecha', 'estado']],
        ['tipo', 'string', false, undefined, undefined, [
          { value: 'alquiler', label: 'Alquiler' },
          { value: 'comision', label: 'Comision' },
          { value: 'gasto', label: 'Gasto' },
          { value: 'ajuste', label: 'Ajuste' },
          { value: 'otro', label: 'Otro' },
        ]],
        ['concepto', 'string'],
        ['importe', 'number'],
        ['pago_id', 'string', false, 'pagos_alquiler', ['numero_recibo', 'fecha_pago']],
        ['cuota_id', 'string', false, 'cuotas_alquiler', ['numero_cuota', 'fecha_vencimiento']],
        ['movimiento_caja_id', 'string', false, 'movimientos_caja', ['fecha', 'concepto']],
      ]),
    },
  },
  {
    key: 'expenses',
    title: 'Egresos',
    singular: 'egreso',
    description: 'Egresos y conceptos adicionales vinculados a cada locación.',
    table: {
      name: 'pagos_alquiler',
      primaryKey: 'id',
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['contrato_id', 'string', true, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['fecha_pago', 'datetime'],
        ['concepto', 'string'],
        ['detalle_otros_importes', 'string', false],
        ['otros_importes', 'number', false],
        ['gastos_adicionales', 'number', false],
        ['estado', 'string', false],
        ['observaciones', 'string', false],
      ]),
    },
  },
  {
    key: 'agenda',
    title: 'Agenda y alertas',
    singular: 'evento',
    description: 'Recordatorios, vencimientos, cuotas impagas y seguimiento documental.',
    table: {
      name: 'agenda_alertas',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['titulo', 'string'],
        ['tipo', 'string', false, undefined, undefined, [
          { value: 'contrato_por_vencer', label: 'Contrato por vencer' },
          { value: 'cuota_impaga', label: 'Cuota impaga' },
          { value: 'documentacion', label: 'Documentacion' },
          { value: 'recordatorio', label: 'Recordatorio' },
        ]],
        ['fecha', 'datetime'],
        ['estado', 'string', false, undefined, undefined, [
          { value: 'pendiente', label: 'Pendiente' },
          { value: 'en_proceso', label: 'En proceso' },
          { value: 'resuelto', label: 'Resuelto' },
        ]],
        ['contrato_id', 'string', false, 'contratos_alquiler', ['id', 'fecha_inicio', 'fecha_fin']],
        ['propiedad_id', 'string', false, 'propiedades', ['direccion']],
        ['inquilino_id', 'string', false, 'inquilinos', ['nombres', 'apellidos']],
        ['propietario_id', 'string', false, 'propietarios', ['nombres', 'apellidos', 'alias_cbu']],
        ['descripcion', 'string', false],
        ['automatico', 'boolean', false],
        ['fecha_recordatorio', 'datetime', false],
        ['documento_pendiente', 'string', false],
      ]),
    },
  },
  {
    key: 'employees',
    title: 'Empleados',
    singular: 'empleado',
    description: 'Usuarios internos y empleados de la inmobiliaria.',
    table: {
      name: 'empleados',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dni', 'integer', false],
        ['nombres', 'string'],
        ['apellido', 'string', false],
        ['telefono', 'string', false],
        ['celular', 'string', false],
        ['fax', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
        ['ciudad', 'string', false],
        ['codigo_postal', 'string', false],
        ['pais', 'string', false],
        ['foto', 'string', false],
        ['rol', 'string', false, undefined, undefined, [
          { value: 'superadmin', label: 'Super administrador' },
          { value: 'admin', label: 'Administrador' },
          { value: 'empleado', label: 'Empleado' },
        ]],
        ['activo', 'boolean', false],
        ['user_id', 'string', false, 'user_profiles', ['email', 'role']],
      ]),
    },
  },
  {
    key: 'guarantors',
    title: 'Garantes',
    singular: 'garante',
    description: 'Garantes disponibles para asociar a los contratos.',
    table: {
      name: 'garantes',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['nombres', 'string', false],
        ['apellidos', 'string', false],
        ['dni', 'integer', false],
        ['cuit', 'string', false],
        ['telefono', 'string', false],
        ['email', 'string', false],
        ['direccion', 'string', false],
      ]),
    },
  },
  {
    key: 'userRoles',
    title: 'Equipo',
    singular: 'miembro del equipo',
    description: 'Usuarios internos, invitaciones y roles de acceso al sistema.',
    table: {
      name: 'user_profiles',
      primaryKey: 'id',
      canCreate: false,
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['email', 'string', true],
        ['role', 'string', false, undefined, undefined, [
          { value: 'superadmin', label: 'Super administrador' },
          { value: 'admin', label: 'Administrador' },
          { value: 'user', label: 'Usuario sin acceso al panel' },
        ]],
      ]),
    },
  },
  {
    key: 'propertyTypes',
    title: 'Tipos de propiedades',
    singular: 'tipo de propiedad',
    description: 'Configuracion de categorias para clasificar propiedades.',
    table: {
      name: 'tipos_propiedad',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['tipo_propiedad', 'string'],
        ['nombre', 'string'],
        ['descripcion', 'string', false],
      ]),
    },
  },
  {
    key: 'contractTerms',
    title: 'Plazos de contratos',
    singular: 'plazo de contrato',
    description: 'Configuracion de duraciones disponibles para contratos de alquiler.',
    table: {
      name: 'plazos_contrato',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['dias', 'integer', false],
        ['caracter', 'string', false],
        ['equivale', 'string', false],
        ['nombre', 'string'],
        ['meses', 'integer'],
        ['descripcion', 'string', false],
      ]),
    },
  },
  {
    key: 'currencies',
    title: 'Monedas de cobro',
    singular: 'moneda de cobro',
    description: 'Configuracion de monedas disponibles para importes y cobros.',
    table: {
      name: 'monedas_cobro',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['codigo', 'string'],
        ['nombre', 'string'],
        ['simbolo', 'string', false],
        ['dolar', 'number', false],
        ['euro', 'number', false],
      ]),
    },
  },
  {
    key: 'updateTypes',
    title: 'Tipos de actualizacion',
    singular: 'tipo de actualizacion',
    description: 'Configuracion de criterios para actualizar el valor del contrato.',
    table: {
      name: 'tipos_actualizacion_valor',
      primaryKey: 'id',
      columns: columns([
        ['id', 'string', true],
        ['nombre', 'string'],
        ['descripcion', 'string', false],
        ['activo', 'boolean', false],
      ]),
    },
  },
  {
    key: 'agencySettings',
    title: 'Datos y comisión',
    singular: 'configuración',
    description: 'Datos de la inmobiliaria usados en contratos, recibos y cálculos administrativos.',
    table: {
      name: 'configuracion_inmobiliaria',
      primaryKey: 'id',
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['nombre', 'string', false, undefined, undefined, undefined, true],
        ['cuit', 'string', false],
        ['direccion', 'string', false],
        ['telefono', 'string', false],
        ['email', 'string', false],
        ['logo_url', 'string', false],
        ['porcentaje_comision_default', 'number', false, undefined, undefined, undefined, true],
      ]),
    },
  },
  {
    key: 'iclIndices',
    title: 'Índices ICL',
    singular: 'índice ICL',
    description: 'Valores diarios sincronizados desde la API oficial del BCRA.',
    table: {
      name: 'icl_indices',
      primaryKey: 'fecha',
      canCreate: false,
      canDelete: false,
      columns: columns([
        ['fecha', 'date', true],
        ['valor', 'number', true],
        ['created_at', 'datetime', true],
      ]),
    },
  },
  {
    key: 'financialSettings',
    title: 'Configuracion financiera',
    singular: 'configuracion financiera',
    description: 'Parametros para vencimientos, intereses y deuda a hoy.',
    table: {
      name: 'configuracion_financiera',
      primaryKey: 'id',
      canDelete: false,
      columns: columns([
        ['id', 'string', true],
        ['es_principal', 'boolean', false],
        ['dia_vencimiento', 'integer', false, undefined, undefined, undefined, true],
        ['tipo_interes', 'string', false, undefined, undefined, [
          { value: 'mensual', label: 'Mensual' },
          { value: 'diario', label: 'Diario' },
          { value: 'fijo', label: 'Fijo' },
          { value: 'sin_interes', label: 'Sin interes' },
        ], true],
        ['porcentaje_mensual', 'number', false, undefined, undefined, undefined, true],
        ['dias_gracia', 'integer', false, undefined, undefined, undefined, true],
      ]),
    },
  },
]

export function getModule(key: Exclude<ModuleKey, 'dashboard'>): ModuleDefinition {
  return modules.find((module) => module.key === key) ?? modules[0]
}

function columns(
  definitions: Array<
    [
      name: string,
      type: ColumnSchema['type'],
      readOnly?: boolean,
      referenceTable?: string,
      labelColumns?: string[],
      options?: ColumnSchema['options'],
      required?: boolean,
      format?: string,
      multiple?: boolean,
    ]
  >,
): ColumnSchema[] {
  return definitions.map(([name, type, readOnly = false, referenceTable, labelColumns, options, required, format, multiple]) => ({
    name,
    type,
    nullable: !(required ?? ['id', 'fecha_inicio', 'fecha_fin', 'fecha', 'importe', 'estado'].includes(name)),
    required: required ?? ['fecha_inicio', 'fecha_fin', 'fecha', 'importe', 'estado'].includes(name),
    readOnly: readOnly || commonReadOnly.includes(name),
    format,
    reference: referenceTable
      ? {
          table: referenceTable,
          valueColumn: 'id',
          labelColumns: labelColumns ?? ['nombre'],
        }
      : undefined,
    options,
    multiple,
  }))
}
